---
title: "R Notebook"
output: html_notebook
---

options(warn = -1) # Turn off warnings

```{r}
library(tidyverse)
```

```{r}

#plot(select(iris, -Species))
#qplot(select(iris, -Species))
```

```{r}
qplot(displ, hwy, data = mpg)
```

```{r}
qplot(displ, hwy, color=class, data = mpg)
```

```{r}
qplot(displ, data = mpg)
```


```{r}
qplot(displ, data = mpg, geom = c('bar'))
```

# mpg %>% qplot(displ, hwy)

# qplot(displ, hwy, mpg)

```{r}
#install.packages("plotly")
library(plotly)
```

```{r}
head(mpg)
```

```{r}
fig1 <- mpg %>%
    plot_ly(
        x         = ~hwy, 
        y         = ~cty, 
        size      = ~displ, 
        type      = 'scatter', 
        color     = ~class,
        mode      = "markers",
        hovertext = ~manufacturer,
        height    = 500, width = 750)

fig1
```


```{r}
fig2 <- iris %>%
    plot_ly(
        x         = ~Petal.Length, 
        y         = ~Petal.Width, 
        size      = ~Sepal.Length, 
        color     = ~Sepal.Width,
        symbol    = ~Species,
        type      = "scatter", 
        mode      = "markers",
        height    = 500, width = 750)

fig2
```

# ?plot_ly

```{r}
ggplotly()
```


```{r}
ggplotly(height=200, width=350)
```

# ?ggplotly

```{r}
head(filter(mpg, hwy > 0))
```
```


